SIOCSARP: Invalid argument
arp: cannot set entry on line 457 of etherfile /tmp/arp.txt !
sudo: unable to resolve host lxc-457: Connection refused
Waiting for 1 secs ...
Connecting ...
Traceback (most recent call last):
  File "/home/kronos/ns-allinone-3.29/ns-3.29/examples/vt_experiments/common/tcp_client.py", line 19, in <module>
    client.connect((serverIP, 9999))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 110] Connection timed out
TracerID: 0, STOP Command received. Stopping tracer ...
